import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';

const baseURL = '/BerbagiCeritaku/';

self.addEventListener('push', event => {
  const data = event.data.json();
  const options = {
    body: data.options.body,
    icon:  `${baseURL}images/icon.png`,
    badge: `${baseURL}images/icon.png`,
  };
  
  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

self.addEventListener('notificationclick', event => {
  event.notification.close();

  const urlToOpen = event.notification.data || 'https://xraxs.github.io/BerbagiCeritaku/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(clientList => {
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});

// Precache all assets generated by webpack build
precacheAndRoute(self.__WB_MANIFEST);

// Cache HTML pages with Network First strategy (try network first, fallback cache)
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages-cache',
    networkTimeoutSeconds: 3, // Optional timeout to fallback faster
  })
);

// Cache CSS, JS, images with Cache First strategy
registerRoute(
  ({ request }) => ['style', 'script', 'image'].includes(request.destination),
  new CacheFirst({
    cacheName: 'assets-cache',
  })
);
